import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import NavBar from "@/packages/ui/molecules/navBar";
import { Geist, Geist_Mono } from "next/font/google";
import { authOptions } from "./api/auth/[...nextauth]/options";
import StoreProvider from "@/packages/providers/store.provider";
import { ThemeProvider } from "@/packages/providers/theme.provider";
import SessionProvider from "@/packages/providers/session.provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions); 
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <SessionProvider session={session}>
            <ThemeProvider>
              <NavBar />
              {children}
            </ThemeProvider>
          </SessionProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
